personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
notify = ["/Users/npiv/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/npiv/code/ankimaker"]
trust_level = "trusted"

[projects."/Users/npiv/code/data"]
trust_level = "trusted"

[projects."/Users/npiv"]
trust_level = "untrusted"

[projects."/Users/npiv/code/lifedashboard"]
trust_level = "trusted"

[projects."/Users/npiv/code/phrase-learner"]
trust_level = "trusted"

[projects."/Users/npiv/code/timerapp"]
trust_level = "trusted"

[projects."/Users/npiv/.codex/skills"]
trust_level = "untrusted"


sandbox_mode = "workspace-write"

[projects."/Users/npiv/code/dotfiles"]
trust_level = "trusted"

[projects."/Users/npiv/code"]
trust_level = "untrusted"

[projects."/Users/npiv/code/lore"]
trust_level = "trusted"

[projects."/Users/npiv/work/tries/limatic_new_site"]
trust_level = "trusted"

[projects."/Users/npiv/work/tries/factorio"]
trust_level = "trusted"

[projects."/Users/npiv/code_eu/eu/ecmp-ms-user"]
trust_level = "trusted"

[projects."/Users/npiv/code_eu/eu"]
trust_level = "trusted"

[projects."/Users/npiv/code_eu/eu/ecmp-ms-ontology-management"]
trust_level = "trusted"

[projects."/Users/npiv/code_eu/eu/ecmp-ms-incident-management"]
trust_level = "trusted"

[projects."/Users/npiv/code/kbc/data"]
trust_level = "trusted"

[projects."/Users/npiv/work/tries/casa_iribarne"]
trust_level = "trusted"

[projects."/Users/npiv/work/tries/luke"]
trust_level = "trusted"

[projects."/Users/npiv/work/tries/chessmood"]
trust_level = "trusted"

[projects."/Users/npiv/code/whitelane"]
trust_level = "trusted"

[sandbox_workspace_write]
  network_access = true

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."github@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-07-12T12:06:15Z"
source_type = "local"
source = "/Users/npiv/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-12T15:38:09Z"
source_type = "local"
source = "/Users/npiv/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[desktop]
default-service-tier = "priority"
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"

[desktop.open-in-target-preferences]
global = "vscode"

[desktop.open-in-target-preferences.perPath]
"/Users/npiv/code/axonpoc" = "vscode"
"/Users/npiv/code/lore" = "intellij"
"/Users/npiv/code/proxymoxy" = "vscode"

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/npiv/.codex"
CODEX_HOME = "/Users/npiv/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,e74b67ab909392b37f7aef14977fce7aa80cfa02ade5491f30abcdbcb9e69f33"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.51957"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false
