
live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
#[shell]
#program = "/bin/bash"
#args = ["-l", "-c", "zellij"]

[env]
TERM = "xterm-256color"

[window]
# startup_mode = "SimpleFullscreen"
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.8
# blur = true


[window.padding]
x = 8
y = 8

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"
