
live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

[shell]
program = "/bin/bash"
args = ["-l", "-c", "zellij"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1


[window.padding]
x = 25
y = 20

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"
