
live_config_reload = true
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
# import = ["~/.config/alacritty/tokyo/night.toml"]
#[shell]
#program = "/bin/bash"
#args = ["-l", "-c", "zellij"]

[env]
TERM = "xterm-256color"

[window]
# startup_mode = "SimpleFullscreen"
decorations = "None"
dynamic_padding = true
# opacity = 0.9
# blur = true


[window.padding]
x = 8
y = 8

[font]
size = 14

[font.normal]
family = "JetbrainsMono Nerd Font"

