#!/bin/bash

# Set variables
INPUT_FILE="$1"
API_KEY="$OPENAI_API_KEY"

# Check if input file is provided
if [ -z "$INPUT_FILE" ]
then
  echo "Please provide an input file"
  exit 1
fi

ffmpeg -i "$INPUT_FILE" -vn -loglevel error -acodec libmp3lame -q:a 2 "$INPUT_FILE".mp3
echo "transcribing $INPUT_FILE.mp3 to $INPUT_FILE.vtt"
curl --request POST \
     --url https://api.openai.com/v1/audio/transcriptions \
     --header "Authorization: Bearer $API_KEY" \
     --header 'Content-Type: multipart/form-data' \
     --form "file=@$INPUT_FILE.mp3" \
     --form "model=whisper-1" \
     --form "response_format=vtt" \
     -s \
     -o "$INPUT_FILE.vtt"
