#!/bin/bash

# Set variables
INPUT_FILE="$1"
API_KEY="$OPENAI_API_KEY"

# Check if input file is provided
if [ -z "$INPUT_FILE" ]
then
  echo "Please provide an input file"
  exit 1
fi

i=0
for file in *.mkv
do
  i=$((i + 1))
  ffmpeg -i "$file" -vn -acodec libmp3lame -q:a 2 audio.mp3
  echo "transcribing $file"
  curl --request POST \
       --url https://api.openai.com/v1/audio/transcriptions \
       --header "Authorization: Bearer $API_KEY" \
       --header 'Content-Type: multipart/form-data' \
       --form "file=audio.mp3" \
       --form "model=whisper-1" \
       --form "response_format=vtt" \
       -o "$file.vtt"
  rm audio.mp3
done
